name: armTemplateDeployment

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS}}

      - name: Azure deploy ARM template
        uses: Azure/cli@v1
        with:
          inlinescript: |
            az deployment sub create --location "westeurope" --template-file ./arm-templates/resourcegroup.json

      - name: Deploy resource group
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          deploymentName: rg-githubactions
          region: westeurope
          subscriptionId: 6fbf6081-bf6f-4419-93b2-b19e973cc345
          template: ./arm-templates/resourcegroup.json

      - name: Deploy storage account
        uses: Azure/arm-deploy@v1
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rg-githubactions
          region: westeurope
          subscriptionId: 6fbf6081-bf6f-4419-93b2-b19e973cc345
          template: ./arm-templates/storageaccount.json
          parameters: ./arm-templates/storageaccount.parameters.json
          deploymentMode: incremental

      - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri}}
