# This is a basic workflow to help you get started with Actions

name: armTemplateDeploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true

      - name: Azure deploy ARM template
        uses: Azure/cli@v1
        with:
          inlinescript: |
            az deployment sub create --location "westeurope" --template-file ./arm-templates/resourcegroup.json


      - name: Deploy Azure Resource Manager (ARM) Template
        uses: Azure/arm-deploy@v1
        with:
          scope: resourcegroup
          deploymentName: rg-githubactions
          subscriptionId:  6fbf6081-bf6f-4419-93b2-b19e973cc345
          template: ./arm-templates/accountstorage.json


      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Cau lidi!

